const ActionTypes = {
  // General
  SHOW_ALERT: 'SHOW_ALERT',
  HIDE_ALERT: 'HIDE_ALERT',
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',
  showProgress: 'showProgress',
  hideProgress: 'hideProgress',
  GET_PAGES: 'GET_PAGES',
  GET_FAQ: 'GET_FAQ',
 

  // User
  USER_DATA: 'USER_DATA',
  LOGOUT: 'LOGOUT',
  IS_LOGIN: 'IS_LOGIN',

  // All Users
  GET_ALLUSERS: 'GET_ALLUSERS',
  RESET_GET_ALLUSERS: 'RESET_GET_ALLUSERS',
  Is_Subscribed: 'Is_Subscribed',

  GET_ALLFRIENDS: 'GET_ALLFRIENDS',
  RESET_GET_ALLFRIENDS: 'RESET_GET_ALLFRIENDS',
  GET_ALLFRIENDS_COUNT: 'GET_ALLFRIENDS_COUNT',

  GET_ALLREQUESTS: 'GET_ALLREQUESTS',
  RESET_GET_ALLREQUESTS: 'RESET_GET_ALLREQUESTS',

  GET_ACTIVEFRIENDS: 'GET_ACTIVEFRIENDS',

  get_notification: 'get_notification',
  reset_notification: 'reset_notification',
  notificationSwitch: 'notificationSwitch',
  GET_NOTIFICATION_COUNT: 'GET_NOTIFICATION_COUNT',

  GET_MY_SUBSCRIPTION: 'GET_MY_SUBSCRIPTION',
  GET_SUBSCRIPTIONS: 'GET_SUBSCRIPTIONS',

  GET_CARDS: 'GET_CARDS',
  GET_ADVERTS: 'GET_ADVERTS',

  // Chat
  GET_CHAT: 'GET_CHAT',
  GET_INBOX_COUNT: 'GET_INBOX_COUNT',
  RESET_CHAT: 'RESET_CHAT',
  UPDATE_CHAT: 'UPDATE_CHAT',
  CHAT_HEAD: 'CHAT_HEAD',
  DELETE_HEAD: 'DELETE_HEAD',
  RESET_CHATHEADS: 'RESET_CHATHEADS',
  STORE_CARD: 'STORE_CARD',
  DELETE_CARD: 'DELETE_CARD',
};

export default ActionTypes;
